#version: "3.9"
#services:
#  mysqlservice:
#    image: mysql:5.7
#    ports:
#      - "3306:3306"
#    container_name: mysql-container-micro1
#    networks:
#      - user-pizza-net
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USERNAME: root
#      MYSQL_PASSWORD: root
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#
#  mongodbservice:
#    image: mongo:latest
#    container_name: mongodb-container2
#    networks:
#      - user-pizza-net
#    ports:
#      - "27017:27017"
#
#  userauthservice:
#    container_name: user-auth-service1
#    build: UserAuthService/
#    networks:
#      - user-pizza-net
#    ports:
#      - "8086:8086"
#    depends_on:
#      - mysqlservice
#    restart: always
#
#  userpizzaservice:
#    container_name: user-pizza-service1
#    build: UserPizzaService/
#    networks:
#      - user-pizza-net
#    ports:
#      - "8083:8083"
#    depends_on:
#      - mongodbservice
#    restart: always
#
#  apigateway:
#    container_name: SpringAPIGateway
#    build: SpringAPIGateway/
#    networks:
#      - user-pizza-net
#    ports:
#      - "9002:9002"
#    depends_on:
#      - userauthservice
#      - userpizzaservice
#      - eureka-service
#
#  eureka-service:
#    container_name: eureka-service
#    build: EurekaServer/
#    restart: always
#    networks:
#      - user-pizza-net
#    ports:
#      - "8761:8761"
#
#networks:
#  user-pizza-net:
#    driver: bridge
